version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: [ “CMD-SHELL”, “pg_isready” ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: ./
    container_name: server_container
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    env_file:
      - ./.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  pgdata:
  redis-data: